# Generated by Django 5.0.1 on 2024-04-01 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0003_industry"),
    ]

    operations = [
        migrations.CreateModel(
            name="Energy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("energy", models.FloatField()),
                (
                    "item_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="recipe.item"
                    ),
                ),
            ],
        ),
    ]
