# Generated by Django 5.0.1 on 2024-04-12 22:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0004_energy"),
    ]

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("item_name", models.CharField(max_length=64)),
                ("required_energy", models.FloatField()),
                ("capital", models.IntegerField()),
                ("out_quantity", models.FloatField()),
            ],
        ),
    ]
