# Generated by Django 5.0.1 on 2024-04-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0005_requirement"),
    ]

    operations = [
        migrations.AddField(
            model_name="recipe",
            name="name",
            field=models.CharField(default="try", max_length=64, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="recipe",
            name="id_recipe",
            field=models.CharField(max_length=64, unique=True),
        ),
    ]
