# Generated by Django 5.0.1 on 2024-04-29 15:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("recipe", "0006_recipe_name_alter_recipe_id_recipe"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("task", models.CharField(max_length=64)),
            ],
        ),
    ]
